# MIT License
#
# Copyright (c) 2025 Istituto Italiano di Tecnologia (IIT)
#                    Author: Davide De Tommaso (davide.detommaso@iit.it)
#                    Project: Dockyman
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

services:

  pyicub:
    image: ${BASE_PROJECT_NAME}
    container_name: pyicub

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: ${PYICUB_IMAGE}
        LOCAL_USER_UID: ${LOCAL_USER_UID:-1000}
        LOCAL_USER_GID: ${LOCAL_USER_GID:-1000}

    env_file:
      - .env

    command: ["/bin/bash", "-c", "terminator 2>/dev/null & bash $ROBOT_CODE/pyicub/scripts/start.sh"]
    
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true

    working_dir: /workdir

    runtime: ${DOCKER_RUNTIME:-runc}

    environment:
      - DISPLAY=${DISPLAY:-:0}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR:-/tmp}/pulse/native
      - PULSE_COOKIE=/run/pulse/cookie
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/tmp}
      - XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
      - QT_X11_NO_MITSHM=1
      - NO_AT_BRIDGE=1
      - LIBGL_ALWAYS_SOFTWARE=false
      - NVIDIA_VISIBLE_DEVICES=${GPU_DEVICES:-none}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SSH_AUTH_SOCK=/ssh-agent

    volumes:
      - ./workdir:/workdir
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.config/pulse/cookie:/run/pulse/cookie
      - ${XDG_RUNTIME_DIR:-/tmp}/pulse:${XDG_RUNTIME_DIR:-/tmp}/pulse
      - ${XDG_RUNTIME_DIR:-/tmp}/dconf:${XDG_RUNTIME_DIR:-/tmp}/dconf
      - ${HOME}/.gitconfig:/home/icub/.gitconfig:ro
      - ${HOME}/.ssh:/home/icub/.ssh:ro
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent

    profiles:
      - backend

  pyicub.frontend:
    image: ${PYICUB_FRONTEND_IMAGE}
    container_name: pyicub-frontend

    env_file:
      - .env

    environment:
      - SSH_AUTH_SOCK=/ssh-agent

    network_mode: host

    depends_on:
      - pyicub

    volumes:
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}/.ssh:/root/.ssh:ro
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent

    profiles:
      - frontend
